### ISSUE TITLE
Arduino Uno Compatibility

### ISSUE THREAD

**Issue by MoBross** [freeasabeer/SpaceMouse#1]
Hi
I'm Somewhat new to arduino,
I only have an arduino starter kit with arduino uno board, joystick module and some more.
will this sketch work with arduino uno?
If not what modifications do i need to do in the sketch?

best
moshik

**Comment by freeasabeer** [comment]
No, it won't work.
With an Arduino Uno it is not possible to use the USB port as a device, it can only be used to download sketches to the board.
You definitively need an Arduino micro pro board to be able to use the USB port as a device.
Like this one: https://www.amazon.fr/ARCELI-Atmega32U4-Bootloadered-d%C3%A9veloppement-Microcontr%C3%B4leur/dp/B07J2Q3ZD5

**Comment by MoBross** [comment]
Understood
Thanx
